Docs: Line wrap long lines of text for a display
AcademySoftwareFoundation/OpenTimelineIO pull request #1140
Opened 2021-11-09 15:36 UTC by ThomasWilshaw

**Link the Issue(s) this Pull Request is related to.**

Fix #1139 
**Summarize your change.**

The line length of some of the comments in the code blocks was extreamly long making reading it a pain. This PR manually line wraps that to 80 characters. I donlt know if there is a specific convention for this.

2021-11-09 16:56 UTC, meshula approved these changes
I think the unwrapped sources are meant to be easy to edit without having to manually rewrap, but rewrapping is easy, so I'm personally fine with checking it in wrapped.

2021-11-09 17:04 UTC, ssteinbach commented
This documentation is actually autogenerated, by extracting from pydoc directly from the classes.  So the line breaking would have to happen in this script:

https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/27ed98663fb4e20b9e187f85b34f5a58f9bd60d9/src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py#L319

2021-11-09 17:26 UTC, meshula requested changes
Switching to Request Changes, per @ssteinbach's note.

2021-11-09 17:58 UTC, ThomasWilshaw commented
Might it be better to wrap the lines [here](https://github.com/PixarAnimationStudios/OpenTimelineIO/blob/3e4b4591409a4afce92ca7b2bc9cb94c7f756426/src/py-opentimelineio/opentimelineio-bindings/otio_serializableObjects.cpp#L702) rather than trying to do it automatically and risking wrapping very long commands that should probably stay on a single line?

2021-11-09 18:28 UTC, ssteinbach commented
Thats an option.  There are also tools in python for wrapping text:
https://docs.python.org/3/library/textwrap.html

@meshula I'm a little surprised our clang format pass didn't wrap these lines, actually.

2021-11-09 19:30 UTC, JeanChristopheMorinPerso commented
@ssteinbach those string are prefixed with `R`, which I guess it's kind of a raw string. It would be weird if clang formatted these raw string no?

2021-11-09 21:23 UTC, ThomasWilshaw commented
How does that look? It's been a while since Ive written any Python code so there may be a nicer/better way to do it.

2021-11-09 21:38 UTC, ssteinbach commented
The unit tests check to see if the autogenerated docs have been updated -- you'll need to check in to your branch the updated docs.  You can generate them by using the `make doc-model-update` build target.

2021-11-09 22:28 UTC, ThomasWilshaw commented
Done, but for some reason there has been a change in the text that's nothing to do with the Python code

2021-11-10 18:09 UTC, meshula commented
For certain, we would never want clang-format to interfere with an R"string", as that would interfere with the very purpose of the raw strings.

2021-11-12 17:59 UTC, ThomasWilshaw commented
I've just updated this. I had an older version of OTIO in my Python setup that was messing things up

2022-07-08 01:31 UTC, meshula approved these changes

2022-07-08 01:33 UTC, meshula commented
@ThomasWilshaw Sorry to have missed your request for a review, I just spotted this. Now, there is the CLA to take care of. If you're able to go through the CLA business, we can get this PR moving again. Apologies again.

2022-07-09 10:39 UTC, ThomasWilshaw commented
No problem, sorry I've dropped off the radar for a while, I've been very busy of late. That's the CLA all done, please let me know if there are any other issues.

2022-07-10 00:26 UTC, meshula commented
Looks like CI is stumbling as soon as it hits the py_build_test.  My python-fu is too weak ~ any thoughts on what's tripping it up?

2022-07-10 00:58 UTC, meshula commented on src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py
> +            if(cl.__doc__ != None):
```suggestion
            if(cl.__doc__ is not None):
```

2022-07-10 01:01 UTC, meshula commented on src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py
> +                    line = textwrap.wrap(line, width=100, expand_tabs=False, replace_whitespace=False, drop_whitespace=False, break_long_words=False)
```suggestion
                    line = textwrap.wrap(
                                    line, width=100, 
                                     expand_tabs=False, 
                                     replace_whitespace=False, 
                                     drop_whitespace=False, 
                                     break_long_words=False)
```

2022-07-10 01:05 UTC, meshula commented on src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py
> +                                     break_long_words=False)
```suggestion
                    line = textwrap.wrap(line, width=100,
                                         expand_tabs=False,
                                         replace_whitespace=False,
                                         drop_whitespace=False,
                                         break_long_words=False)
```

2022-07-10 01:14 UTC, meshula commented on src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py
> +                    for l in line: new_docstring.append(l)
```suggestion
                    for wrapped_line in line:
                        new_docstring.append(wrapped_line)
```

2022-07-10 01:21 UTC, meshula commented
@ThomasWilshaw I corrected the PEP8 issues that came up, but it looks like there needs to be a corresponding update to the test suite to accommodate the reformatting?

2022-07-10 01:26 UTC, JeanChristopheMorinPerso commented
I believe `make doc-model-update` should do the trick.

2022-09-12 17:48 UTC, jminor commented
It looks like this PR is almost ready. It just needs `make doc-model-update` and DCO signoff.

2023-01-09 17:11 UTC, ThomasWilshaw commented
Apologies for the massive massive delay on completing this but I think it is all good to go now aside form the DCO stuff. Would someone be able to advise on how I'm supposed to sort that?

2023-01-10 23:58 UTC, meshula commented
The DCO requirement would have needed you to do all your commits with the `-s` argument. That would be tedious to retrofit. Instead, when you are ready to merge, we'll do a squash merge after forcing the DCO to pass. If you could do one last commit, with -s, it'll be easy enough for us to force that DCO signoff to apply to whole thing.

2023-01-11 00:05 UTC, JeanChristopheMorinPerso commented
BTW, you can see the command line to use at https://github.com/AcademySoftwareFoundation/OpenTimelineIO/runs/10531037992.

2023-01-11 00:09 UTC, jminor commented
It is pretty easy to retroactively sign-off all of the commits like this:
```
% git status
...check that you're on the right branch ("line_wrap" in your case)
% git rebase main --signoff
...check that the history looks fine (code is unchanged by this command)
% git push --force
```

The signoff step is intended to make sure you've checked that all of the commits are what you've intended to contribute, and nothing else accidentally got checked in.

2023-01-11 00:16 UTC, jminor commented
Oops, it looks like we're all helping to answer at the same time. I didn't see @meshula 's or @JeanChristopheMorinPerso 's advice before posting. Luckily these are all good, mostly overlapping, options. If the commands above don't work for you, let us know and we can do the step that @meshula suggested on your behalf.

2023-01-11 01:34 UTC, meshula commented
@joshm TIL a non-tedious way to fix the sign-off requirement ;)

2023-01-13 17:59 UTC, meshula commented
> I should signoff any and all commits to this repo

Yes, I have to remind myself as well, to add a `-S` argument to commits.

2023-01-13 18:00 UTC, merged