Import _opentime before actually creating the bindings for _otio
AcademySoftwareFoundation/OpenTimelineIO pull request #1396
Opened 2022-09-17 19:54 UTC by JeanChristopheMorinPerso

I noticed that doing `python -c 'import opentimelineio._otio'` was not working. It was resulting in an import error:
```
ImportError: arg(): could not convert default argument 'marked_range: opentime::v1_0::TimeRange' in method '<class 'opentimelineio._otio.Marker'>.__init__' into a Python object (type not registered yet?)
```

This error doesn't normally happen because we usually go through `opentimelineio/__init__.py` which imports `_opentime` before importing `_otio`.

After some searching, I found https://pybind11.readthedocs.io/en/stable/advanced/misc.html#partitioning-code-over-multiple-extension-modules which describes some options to fix this. This PR implements the simplest option out there, which is to import `_opentime` before actually creating the `_otio` bindings.

This should be harmless because it is going to be a no-op when importing OTIO normally (via `import opentimelineio`). It will be a no-op in this case bacause Python doesn't re-import a package if imported twice.

2022-09-17 20:03 UTC, meshula requested changes
could you make a small grammatical tweak please?

2022-09-17 20:03 UTC, meshula commented on src/py-opentimelineio/opentimelineio-bindings/otio_bindings.cpp
> +    // for _otio. This allows to import _otio without
to import -> the import of

2022-09-18 04:03 UTC, meshula approved these changes
looks good!

2022-09-18 05:15 UTC, ssteinbach approved these changes
nice catch.  LGTM

2022-09-18 05:40 UTC, merged